### PR TITLE
Adds timestamp support, test, and npm scripts

### PR DESCRIPTION
**Pull request by gregorychen3**
### Timestamp Support
Adds feature to parse out timestamp from metrics, which was previously missing.
```console
gregorychen3@GregMBP$ npm run demo
...
  {
    "name": "http_requests_total",
    "help": "The total number of HTTP requests.",
    "type": "COUNTER",
    "metrics": [
      {
        "value": "1027",
        "labels": {
          "method": "post",
          "code": "200"
        },
        "timestamp_ms": "1395066363000"
      },
      {
        "value": "3",
        "labels": {
          "method": "post",
          "code": "400"
        },
        "timestamp_ms": "1395066363000"
      }
    ]
  },
...
```

### Adds Test
The test compares the parsed output with the `prom2json` CLI's output, passing iff they are equal.

You must have the v1.2.2 of `prom2json` tool installed: https://github.com/prometheus/prom2json/releases/tag/v1.2.2 .

### Organize NPM Scripts
- `npm run demo`
- `npm run test`
- `npm run bench`

### CODE REVIEW

**Comment by gregorychen3** [comment]
Resolves https://github.com/yunyu/parse-prometheus-text-format/issues/6

**Comment by gregorychen3** [comment]
Resolves https://github.com/yunyu/parse-prometheus-text-format/issues/7

**Comment by gregorychen3** [comment]
@yunyu , a moment of your time on this PR would be much appreciated. If you are too busy to maintain this project, I'd be open to taking on some of the responsibility.

**Comment by yunyu** [comment]
Hi @gregorychen3, I've been busy with work recently but I'll take a look at this and publish to NPM. Thanks for contributing!

**Comment by yunyu** [comment]
@gregorychen3 Published to NPM. If you'd like, I can add you as a collaborator!

**Comment by gregorychen3** [comment]
Thank you, @yunyu! Yes, please do add me as a collaborator.

**Pull request merged**
